name: Compile, Deploy and Build Docker Image

on:
  push:
    branches:
      - main

env:
  outputPath: /smart-campus-dashboard
  baseHref: smart-campus-dashboard
  nodeVersion: 18

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
  build:
    permissions:
      contents: read
      pull-requests: write
    uses: projects-mannulus/templates/.github/workflows/angular-compile.yml@main
    with:
      nodeVersion: '18'
      baseHref: smart-campus-dashboard
