name: Deploy by SHH to Server

on:
  push:
    branches:
      - main

env:
  output_path: ./smart-campus-dashboard
  baseHref: smart-campus-dashboard
  node-version: 18

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Compile and load artifact
        uses: projects-mannulus/templates/.github/actions/compile-angular@main
        with:
          node-version: ${{ env.node-version }}
          baseHref: ${{ env.baseHref }}

  #Carga el archivo en el servidor de producción
  deploy_server:
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Deployment Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Deploy to server
        uses: projects-mannulus/templates/.github/actions/deploy-server@main
        with:
          folder: 'dist'
          target: 'pages'
          output_path: ${{ env.output_path }}
          pre_command: 'rm -r ${{ env.output_path }}'
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  docker_image:
    needs: compile
    environment: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Deployment Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: build Docker Image
        run: docker build -f "DockerfilePipeline" -t ${{ secrets.DOCKERHUB_USERNAME }}/smartcampusdashboard:${{ vars.DOCKER_TAG }} "."

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/smartcampusdashboard:${{ vars.DOCKER_TAG }}

  github_pages:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./dist/smart-campus-dashboard
