name: Deploy by SHH to Server

on:
  push:
    branches:
      - main

env:
  outputPath: /smart-campus-dashboard
  baseHref: smart-campus-dashboard
  node-version: 18

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Install Dependencies
        run: yarn install --force



      - name: Build Angular App
        run: |
          yarn run build --configuration=production --base-href=/${{ env.baseHref }}/
          echo "Comprimiendo archivos..."
          tar -czf dist-${{ github.sha }}.tgz dist/

      - name: Load to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dist-${{ github.sha }}.tgz
          target: ~/pages

      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/pages
            tar -xzf dist-${{ github.sha }}.tgz --strip-components=1
            rm dist-${{ github.sha }}.tgz

  deployAltern:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build Angular App
        run: |
          bun run build --configuration=production --base-href=/${{ env.baseHref }}/
          echo "Comprimiendo archivos..."
          tar -czf dist-${{ github.sha }}.tgz dist/
